{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/customauthfinishauthenticationchallenge\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationChallenge\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error describing cause of failure of the previous challenge response."},{"type":"text","text":" "},{"type":"text","text":"Possible error domains: ONGAuthenticatorRegistrationErrorDomain, ONGGenericErrorDomain"}],"kind":"symbol","metadata":{"role":"symbol","title":"error","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:13OneginiSDKiOS39CustomAuthFinishAuthenticationChallengeP5errors5Error_pSgvp","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationChallenge"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/CustomAuthFinishAuthenticationChallenge/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error describing cause of failure of the previous challenge response."},{"type":"text","text":" "},{"type":"text","text":"Possible error domains: ONGAuthenticatorRegistrationErrorDomain, ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationChallenge\/error","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/customauthfinishauthenticationchallenge\/error"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/CustomAuthFinishAuthenticationChallenge":{"role":"symbol","title":"CustomAuthFinishAuthenticationChallenge","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomAuthFinishAuthenticationChallenge"}],"abstract":[{"type":"text","text":"Represents authentication with custom authenticator challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomAuthFinishAuthenticationChallenge"}],"url":"\/documentation\/oneginisdkios\/customauthfinishauthenticationchallenge"}}}